site_name:          Contour.jl
repo_url:           https://github.com/tlycken/Contour.jl
site_description:   Documentation for Contour.jl
site_author:        tlycken

theme:              readthedocs
extra_css:
    - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Contour.jl:
    - index.md
    - tutorial.md
    - reference.md
